#!/bin/sh

if [ $1 = "finder" ]; then
    osascript \
    -e 'tell application "Finder"' \
        -e 'set myW to make new Finder window' \
        -e 'set target of myW to home' \
        -e 'activate' \
    -e 'end tell'

elif [ $1 = "safari" ]; then
    osascript \
    -e 'tell application "Safari"' \
        -e 'make new document' \
        -e 'activate' \
    -e 'end tell' \
    || open -a /Applications/Safari.app

elif [ $1 = "firefox-nightly" ]; then
    osascript \
    -e 'tell application "System Events"' \
        -e 'tell process "Firefox Nightly"' \
            -e 'click menu item "New Window" of menu "File" of menu bar 1' \
            -e 'activate' \
        -e 'end tell' \
    -e 'end tell' \
    -e 'tell application "Firefox Nightly"' \
    -e 'end tell' \
    || open -a /Applications/Firefox\ Nightly.app

elif [ $1 = "iterm2-test" ]; then
    osascript \
    -e 'if application "Finder" is frontmost then' \
        -e 'tell application "Finder" to set dir_path to quoted form of (POSIX path of (first item of (get selection as alias list) as alias))' \
    -e 'else' \
        -e 'set dir_path to ""' \
    -e 'end if' \
    -e 'tell application "iTerm2"' \
        -e 'set win to (create window with default profile)' \
        -e 'if dir_path is not equal to ""' \
            -e 'set sesh to (current session of win)' \
            -e 'tell sesh to write text "cd " & dir_path & ";clear"' \
        -e 'end if' \
    -e 'end tell' \
    || open -a /Applications/iTerm.app

elif [ $1 = "iterm2" ]; then
    osascript \
    -e 'tell application "iTerm2" to create window with default profile' \
    || open -a /Applications/iTerm.app

elif [ $1 = "kitty-test" ]; then
    osascript \
    -e 'set rng to (application "kitty" is running)' \
    -e 'activate application "kitty"' \
    -e 'if rng then' \
        -e 'tell application "System Events"' \
            -e 'keystroke "n" using command down' \
        -e 'end tell' \
    -e 'end if'


elif [ $1 = "hyper" ]; then
    osascript \
    -e 'tell application "System Events"' \
        -e 'tell process "Hyper"' \
            -e 'click menu item "New Window" of menu "Shell" of menu bar 1' \
            -e 'activate' \
        -e 'end tell' \
    -e 'end tell' \
    || open -a /Applications/Hyper.app

elif [ $1 = "sublime-text" ]; then
    osascript \
    -e 'tell application "System Events"' \
        -e 'tell process "Sublime Text"' \
            -e 'click menu item "New Window" of menu "File" of menu bar 1' \
            -e 'activate' \
        -e 'end tell' \
    -e 'end tell' \
    || open -a /Applications/Sublime\ Text.app
fi


