#!/bin/sh

if [ $1 = "finder" ]; then
	osascript <<-EOD
		tell application "Finder"
			set myW to make new Finder window
			set target of myW to home
			activate
		end tell
	EOD

elif [ $1 = "safari" ]; then
	{
	osascript <<-EOD
		tell application "Safari"
			make new document
			activate
		end tell
	EOD
	} || open -a /Applications/Safari.app

elif [ $1 = "iterm2" ]; then
	{
	osascript <<-EOD
		tell application "iTerm2" 
			create window with default profile
			activate
		end tell
	EOD
	} || open -a /Applications/iTerm.app

elif [ $1 = "vscode" ]; then
	{
    /opt/homebrew/bin/code -n
  }
fi