#! /bin/sh


~/.fehbg
xrdb -merge ~/.Xresources

pkill picom
picom --experimental-backends --backend glx &
pkill sxhkd
sxhkd &
nm-applet &
enpass -minimize &
bspc config ignore_ewmh_focus true

bspc rule -a firefoxdeveloperedition -o desktop=^2 focus=off; firefox-developer-edition &

bspc rule -a Evolution -o desktop=^6 focus=off; evolution &
bspc rule -a Franz -o desktop=^6 focus=off; franz &

bspc rule -a firefoxdeveloperedition -o desktop=^7 focus=off; firefox-developer-edition --new-window https://asana.com &
bspc rule -a Joplin -o desktop=^7 focus=off; joplin-desktop &

$HOME/.config/polybar/launch_polybar.sh
