#! /bin/sh
xrandr -s 2560x1600 
~/.fehbg
xrdb -merge ~/.Xresources

pkill sxhkd
sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_radius	       0	
bspc config border_width         2 
bspc config window_gap           0 
bspc config top_padding          0 
bspc config left_padding         0
bspc config right_padding        0
bspc config bottom_padding       0
bspc config normal_border_color  "#000000"
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

