#! /bin/sh
if grep -q ^flags.*\ hypervisor /proc/cpuinfo ; then
  $HOME/.config/bspwm/bspwmrc_vm 
  exit 1
fi 


bspc config border_radius	       15	
bspc config border_width         0 
bspc config window_gap           30 
bspc config top_padding          70 
bspc config left_padding         50
bspc config right_padding        50
bspc config bottom_padding       30
bspc config normal_border_color  "#000000"
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

profile="$(autorandr | grep current | awk '{ print $1 }')"
reorderfile="$HOME/.config/autorandr/$profile/bspwm_reorder"
echo "$reorderfile"
if test -f "$reorderfile"; then
  echo 'testeeee'
  $reorderfile
else
  $HOME/.config/autorandr/scripts/bspwm_reorder
fi

$HOME/.config/bspwm/autostart
